version: 1.3.0.{build}

branches:
  only:
    - master

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=4

  matrix:
    - ARCH: x64
      COMPILER: VS2019
      QTDIR: C:\Qt\6.2.0\msvc2019_64

    - ARCH: x64
      COMPILER: Clang

image:
  - Visual Studio 2019
  - macOS-Mojave
platform:
  - x64
configuration:
  - Release


matrix:
  exclude:
    # Exclude invalid options
    - image: Visual Studio 2019
      COMPILER: CLang

    - image: macos-mojave
      COMPILER: VS2019

for:
  - # Windows
    matrix:
      only:
        - image: Visual Studio 2019

    before_build:
      - set SOURCEDIR=%cd%
      - call %QTDIR%\bin\qtenv2.bat
      - cd /D %SOURCEDIR%
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    build_script:
      - mkdir .\build
      - cd .\build
      - cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DVERSION=%APPVEYOR_BUILD_VERSION% ../
      - cmake --build .
      - call %QTDIR%\bin\windeployqt --release tidal-rpc.exe

    after_build:
      - echo zipping %APPVEYOR_BUILD_VERSION%
      - 7z a tidal-rpc.zip tidal-rpc.exe *.dll ./imageformats/ ./platforms/ ./styles/

    artifacts:
      - path: build/tidal-rpc.zip
        name: tidal-rpc.zip
        type: zip

    deploy:
      - provider: GitHub
        release: v.$(APPVEYOR_BUILD_VERSION)
        description: "[![Donate](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3XY7W2XHHUZF2&source=url)"
        tag: v.$(APPVEYOR_BUILD_VERSION)
        auth_token:
          secure: StuLm9lo1/+qXVAweuFO3sPdz6r8PlbCmQdpNGQ9VxA529xhLG6YPmi+E2L8SLQk            # your encrypted token from GitHub
        artifact: tidal-rpc.zip          # upload all NuGet packages to release assets
        draft: true
        prerelease: false
        on:
          branch: master                 # release from master branch only

  - # Mac
    matrix:
      only:
        - image: macos-mojave

    before_build:
      - export PATH=$HOME/Qt/6.1.2/clang_64/bin:$PATH

    build_script:
      - mkdir build
      - cd build
      - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DVERSION=$APPVEYOR_BUILD_VERSION ../
      - cmake --build .
      - $HOME/Qt/6.1.2/clang_64/bin/macdeployqt tidal-rpc.app -dmg

    after_build:
      - echo $APPVEYOR_BUILD_FOLDER
      - ls
      - pwd


    artifacts:
      - path: build/tidal-rpc.dmg
        name: tidal-rpc.dmg
        type: file

    deploy:
      - provider: GitHub
        release: v.$(APPVEYOR_BUILD_VERSION)
        description: "[![Donate](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3XY7W2XHHUZF2&source=url)"
        tag: v.$(APPVEYOR_BUILD_VERSION)
        auth_token:
          secure: StuLm9lo1/+qXVAweuFO3sPdz6r8PlbCmQdpNGQ9VxA529xhLG6YPmi+E2L8SLQk              # your encrypted token from GitHub
        artifact: tidal-rpc.dmg          # upload all NuGet packages to release assets
        draft: true
        prerelease: false
        on:
          branch: master                 # release from master branch only
